// Generated by tools/bake_bios.py - do not edit by hand.
//
// PSX BIOS image embedded at compile time. The bytes live next to
// this file as bios.bin and are compiled directly into the
// executable's .rodata.

pub const BIOS_SIZE: usize = 524288;

pub static BIOS: &[u8; BIOS_SIZE] = include_bytes!("bios.bin");
