name: Build RustyStation (macOS)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Install SDL2 dev libraries
        run: brew install sdl2 sdl2_image sdl2_mixer sdl2_ttf

      - name: Build RustyStation
        run: cargo build --release

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: RustyStation-macOS
          path: target/release/
