name: Build RustyStation (Windows)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Install SDL2 dev libraries
        shell: pwsh
        run: |
          vcpkg install sdl2 sdl2-image sdl2-mixer sdl2-ttf

      - name: Build RustyStation
        run: cargo build --release

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: RustyStation-Windows
          path: target/release/
